<?php
/**
 * Created by PhpStorm.
 * User: Leafqun
 * Date: 2018/1/5
 * Time: 15:07
 */

namespace app\index\controller;

use think\Controller;
use think\Db;
use think\exception\DbException;
use think\Request;

class AlarmController extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin:*');
        header('Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept');
    }
    public function getAlarmList(Request $request) {
        $currentPage = $request->param('currentPage');
        if (empty($currentPage)) return ['msg' => '请求参数为空'];
        $city = $request->param('city');
        $startTime = $request->param('startTime');
        $endTime = $request->param('endTime');
        $isFilter = false;
        $map = null;
        if ($city) {
            $map['city'] = $city;
            $isFilter = true;
        }
        if ($startTime && $endTime) {
            $map['create_time'] = ['between time', [$startTime, $endTime]];
            $isFilter = true;
        }
        if (!$isFilter) $map = '1=1';
        try {
            $alarmList = Db::table('alarm')->where($map)->order('create_time', 'desc')->paginate(10, false, [
                'page' => $currentPage,
                'type' => 'bootstrap',
                'var_page' => 'page'
            ]);
            return ['alarmList' => $alarmList];
        } catch (DbException $e) {
        }
    }
}