<?php
/**
 * Created by PhpStorm.
 * User: Leafqun
 * Date: 2017/11/29
 * Time: 23:00
 */

namespace app\index\controller;


use think\Controller;
use think\Db;
use think\Request;

class CommentController extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin:*');
        header('Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept');
    }
    public function getCommentList(Request $request) {
        $postid = $request->param('postid');
        if(empty($postid)) return ['msg' => '请求参数为空'];
        $commentList = Db::table('comments')->alias('c')->join('users u', 'u.id = c.id')
            ->where('c.postid', $postid)->field('c.*, u.nickname, u.avatar')->select();
        return ['commentList' => $commentList];
    }
    public function insertComment(Request $request) {
        $data = $request->param();
        if(count($data) != 3) return ['msg' => '请求参数不完整'];
        $is_insert = Db::table('comments')->insert($data);
        if($is_insert) return ['msg' => 'success'];
        else return ['msg' => '添加失败'];
    }
}